# Site settings
title: frequency
email: kesara@fq.nz
description: > # this means to ignore newlines until "baseurl:"
  frequency is a blog about computer programming, GNU/Linux, AI (Artificial
  Intellignece), FOSS (Free Open Source Software), privacy, information
  security and free culture.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fq.nz/" # the base hostname & protocol for your site
twitter_username: kesara_nr
github_username:  kesara

# Build settings
markdown: kramdown
