# Site settings
title: fq.nz
email: kesara@fq.nz
description: > # this means to ignore newlines until "baseurl:"
  fq.nz is a blog about computer programming, GNU/Linux, AI (Artificial
  Intellignece), FOSS (Free Open Source Software), privacy, information
  security and free culture.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fq.nz/" # the base hostname & protocol for your site
image: "/images/logo.png"
github_username:  kesara

# Build settings
markdown: kramdown
timezone: Pacific/Auckland
permalink: /blog/:year/:month/:day/:title

collections:
    projects:
        output: true

include:
  - .well-known
